Controllers/UpdateIncidentController.cs
using GBCSporting_X_TEAM.Models;
using GBCSporting_X_TEAM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GBCSporting_X_TEAM.Controllers
{
    public class UpdateIncidentController : Controller
    {
        private GbcSportingContext context { get; set; }

        public UpdateIncidentController(GbcSportingContext ctx)
        {
            context = ctx;
        }

        
        public IActionResult Index(int id)
        {

           

            var content = context.Incidents.Where(x => x.TechnicianId == id).
                Include(c => c.Customer).
                Include(p => p.Product).
                Include(t => t.Technician)
                .Select(i => new IncidentViewModel
                {
                    IncidentId = i.IncidentId,
                    ProductId = i.ProductId,
                    TechnicianId = i.TechnicianId,
                    CustomerId = i.CustomerId,
                    Title = i.Title,
                    firstName = i.Customer.FirstName,
                    LastName = i.Customer.LastName,
                    ProductName = i.Product.Name,
                    DateOpened = i.DateOpened,


                });
            ViewBag.Name = context.Technicians.Find(id).Name;


            return View(content);

        }

        [HttpPost]
        public IActionResult Index()
        {  
          
            var TechId = Int32.Parse(Request.Form["techId"]);
            
            var content = context.Incidents.Where(x => x.TechnicianId == TechId).
                Include(c => c.Customer).
                Include(p => p.Product).
                Include(t => t.Technician)
                .Select(i => new IncidentViewModel
                {
                         IncidentId = i.IncidentId,
                         ProductId = i.ProductId,
                         TechnicianId = i.TechnicianId,
                         CustomerId = i.CustomerId,
                         Title = i.Title,
                         firstName = i.Customer.FirstName,
                         LastName = i.Customer.LastName,
                        ProductName = i.Product.Name,
                        DateOpened = i.DateOpened,
                        

                });
                    ViewBag.Name  = context.Technicians.Find(TechId).Name;


            return View(content);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Update";
            var incident = context.Incidents.Find(id);

            IncidentViewModel content = new()
            {
                TechnicianId= incident.TechnicianId,
                IncidentId = incident.IncidentId,
                Title = incident.Title,
                Description = incident.Description,
                DateOpened = incident.DateOpened,
                DateClosed = incident.DateClosed,
                ProductId = incident.ProductId,
                CustomerId = incident.CustomerId,


                TechnicianName = context.Technicians.Find(incident.TechnicianId).Name,
                firstName = context.Customers.Find(incident.CustomerId).FirstName,
                LastName = context.Customers.Find(incident.CustomerId).LastName,
                ProductName = context.Products.Find(incident.ProductId).Name,

               

        };
           

            return View(content);

        }

        [HttpPost]
        public IActionResult Edit(IncidentViewModel incident)
        {
            Incident model = new()
            {
                
                IncidentId = incident.IncidentId,
                ProductId = incident.ProductId,
                CustomerId = incident.CustomerId,
                Title = incident.Title,
                DateOpened = incident.DateOpened,
                DateClosed = incident.DateClosed,
                Description = incident.Description,
                TechnicianId = incident.TechnicianId,
               
                
            };

            if (ModelState.IsValid)
            {
                if (model.IncidentId == 0)
                    context.Incidents.Add(model);
                else
                    context.Incidents.Update(model);
                context.SaveChanges();

                return RedirectToAction("Index", new { id = model.TechnicianId });
            }
            else
            {
                ViewBag.Action = (model.IncidentId == 0) ? "Add" : "Edit";
                incident.TechnicianName = context.Technicians.Find(model.TechnicianId).Name;
                incident.firstName = context.Customers.Find(model.CustomerId).FirstName;
                incident.LastName = context.Customers.Find(model.CustomerId).LastName;
                incident.ProductName = context.Products.Find(model.ProductId).Name;
                return View(incident);
            }
        }

       
    }
}

Views/UpdateIncident/Edit.cshtml
@using GBCSporting_X_TEAM.Models.ViewModels
@model IncidentViewModel

@{
    string title = ViewBag.Action + " Incident";
    ViewBag.Title = title;
}




@*<h4>Technician: @ViewBag.Incidents.Technician.Name</h4>
<h4>Customer: @ViewBag.Incidents.Customer.FirstName</h4>*@

<div class=" container frm-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>

        </div>

    </div>


            <h7><b>Technican:</b>                 @Model.TechnicianName </h7>
<br />
<h7><b>Customer: </b>                    @Model.firstName @Model.LastName</h7>
<br />

<h7><b>Product:</b>                    @Model.ProductName</h7>
<br />

<h7><b>Title:</b>                      @Model.Title</h7>
<br />

<h7><b>Date Opened: </b>                 @Model.DateOpened</h7>
<br />


<form asp-action="Edit" method="post"> 


    <div class="form-group">
        <label asp-for="Description"><b>Description:</b></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>



    <div class="form-group">
        <label asp-for="DateClosed"><b>Date Closed:</b></label>
        <input asp-for="DateClosed" class="form-control">
    </div>
     <input type="hidden" asp-for="IncidentId" />
     <input type="hidden" asp-for="ProductId" />
     <input type="hidden" asp-for="CustomerId" />
    <input type="hidden" asp-for="TechnicianName" />
    <input type="hidden" asp-for="TechnicianId" />
    <input type="hidden" asp-for="ProductName" />
    <input type="hidden" asp-for="firstName" />
    <input type="hidden" asp-for="LastName" />
    <input type="hidden" asp-for="Title" />
     <input type="hidden" asp-for="DateOpened" />
    

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-controller="UpdateIncident" asp-action="Index" asp-route-id="@Model.TechnicianId" class="btn btn-primary">Cancel</a>
</form>
</div>

Views/UpdateIncident/Index.cshtml
@using GBCSporting_X_TEAM.Models.ViewModels
@model IEnumerable<IncidentViewModel>


   
    <h4>Techninican: @ViewBag.Name.ToString()</h4>


   <table class="table table-bordered tbl-hover tbl-fn-sm">
        <thead class="thead">
            <tr>
                <th>Title</th>
                <th>Customer</th>
                <th>Product</th>
                <th>Date Opened</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var incident in Model)
            {
                <tr>
                    @if(incident.Title.Length > 60){
                        <td><span class="fn-md">@incident.Title</span></td>
                    }else{
                        <td>@incident.Title</td>
                    }
                    <td>@incident.firstName @incident.LastName</td>
                    <td>@incident.ProductName</td>
                    <td>@incident.DateOpened</td>
                     <td class="btn-table">
                        <a class=" btn btn-primary btn-sm rounded-2 main-blue " asp-controller="UpdateIncident" 
                        asp-action="Edit"
                        asp-route-id="@incident.IncidentId"
                        >
                            <img height=25 width=25 src="~/img/pencil.png"></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

<a class="btn btn-primary" asp-controller="Home"  asp-action="UpdateIncident">Switch Technician</a>