Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace GBCSporting_X_TEAM.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }
        [Required]
        [StringLength(51, MinimumLength = 1, ErrorMessage = "Firstname requires between 1 and 51 characters")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(51, MinimumLength = 1, ErrorMessage = "Lastname requires between 1 and 51 characters")]
        public string LastName { get; set; }
        [Required]
        [StringLength(51, MinimumLength = 1, ErrorMessage = "Address requires between 1 and 51 characters")]
        public string Address { get; set; }
        [Required]
        [StringLength(51, MinimumLength = 1, ErrorMessage = "City requires between 1 and 51 characters")]
        public string City { get; set; }
        [Required]
        [StringLength(51, MinimumLength = 1, ErrorMessage = "State requires between 1 and 51 characters")]
        public string State { get; set; }
        [Required]
        [StringLength(21, MinimumLength = 1, ErrorMessage = "Post code requires between 1 and 21 characters")]
        public string PostalCode { get; set; }

        [Required]
        public int CountryId { get; set; }
        public Country? Country { get; set; }
        [RegularExpression(@"^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$", ErrorMessage = "Enter phone in format (999) 999-9999 ")]
        public string Phone { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Slug => FirstName?.Replace(' ', '-').ToLower() + '-' + LastName?.Replace(' ', '-').ToLower();

        // navigation property to linking entity
        public ICollection<Registration>? Registrations { get; set; }

    }
}

Models/Registration.cs
namespace GBCSporting_X_TEAM.Models
{
    public class Registration
    {
        // composite primary key
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        // navigation properties
        public Customer? Customer { get; set; }
        public Product? Product { get; set; }


    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using GBCSporting_X_TEAM.Models;


namespace GBCSporting_X_TEAM.Controllers
{
    public class CustomerController : Controller
    {
        private GbcSportingContext context { get; set; }

        public CustomerController(GbcSportingContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Countries = context.Countries
                .OrderBy(x => x.CountryName).ToList(); 
            return View("Edit", new Customer());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Countries = context.Countries
                .OrderBy(x => x.CountryName).ToList();
            var customer = context.Customers.Find(id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            var EmailExists = context.Customers.Where(c => c.Email == customer.Email);
               
            if (!ModelState.IsValid || EmailExists != null)
            {
                if (EmailExists != null) {
                    ViewBag.EmailExists = "Email exists";
                }

                ViewBag.Action = (customer.CustomerId == 0) ? "Add" : "Edit";
                ViewBag.Countries = context.Countries
                .OrderBy(x => x.CountryName).ToList();
                return View(customer);

            } else { 
                if (customer.CustomerId == 0)
                    context.Customers.Add(customer);
                else
                    context.Customers.Update(customer);
                context.SaveChanges();
                return RedirectToAction("Customers", "Home");
            }
            
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            //ViewBag.country = context.Countries.Find(); for later
            var customer = context.Customers.Find(id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            context.Customers.Remove(customer);
            context.SaveChanges();
            return RedirectToAction("Customers", "Home");
        }
    }
}

Controllers/HomeController.cs
using GBCSporting_X_TEAM.Models;
using GBCSporting_X_TEAM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace GBCSporting_X_TEAM.Controllers
{
    public class HomeController : Controller
    {
        private GbcSportingContext context { get; set; }

        public HomeController(GbcSportingContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View(About);
        }

        public IActionResult Products()
        {
            var products = context.Products.OrderByDescending(x => x.ReleaseDate).ToList();
            return View(products);
        }

        public IActionResult Technicians()
        {
            var technician = context.Technicians.OrderBy(x => x.Name).ToList();
            return View(technician);
        }

        public IActionResult Customers()
        {
            var customer = context.Customers.OrderBy(x => x.FirstName).ToList();
            return View(customer);
        }

        public IActionResult Incidents()
        {
            var viewModels = context.Incidents.
                    Include(i => i.Customer).
                    Include(i => i.Product).
                    Select(i => new IncidentViewModel
                    {
                        IncidentId = i.IncidentId,
                        CustomerId = i.CustomerId,
                        Title = i.Title,
                        firstName = i.Customer.FirstName,
                        LastName = i.Customer.LastName,
                        ProductName = i.Product.Name,
                        DateOpened = i.DateOpened
                    });

            return View(viewModels);
        }




        public IActionResult Registrations()
        {
            ViewBag.Customer = context.Customers.OrderBy(x => x.CustomerId).ToList();

            return View();
        }

        public IActionResult UpdateIncident()
        {
            var vm = new IncidentViewModel();
          
            var technicians = context.Technicians;
           
            var technicianList = technicians.Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.TechnicianId.ToString()
                }).ToList();

          
            vm.Technicians = technicianList;
            
            return View(vm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/IncidentController.cs
using Microsoft.AspNetCore.Mvc;
using GBCSporting_X_TEAM.Models;
using System.Linq;
using GBCSporting_X_TEAM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GBCSporting_X_TEAM.Controllers
{
    public class IncidentController : Controller
    {
        private GbcSportingContext context { get; set; }

        public IncidentController(GbcSportingContext ctx)
        {
            context = ctx;
        }


        public IActionResult UIncidents()
        {
            var viewModels = context.Incidents.
                   Include(i => i.Customer).
                   Include(i => i.Product).
                   Include(i => i.Technician).
                   Select(i => new IncidentViewModel
                   {
                       IncidentId = i.IncidentId,
                       CustomerId = i.CustomerId,
                       Title = i.Title,
                       firstName = i.Customer.FirstName,
                       LastName = i.Customer.LastName,
                       ProductName = i.Product.Name,
                       DateOpened = i.DateOpened,
                       TechnicianId = i.Technician.TechnicianId
                   }) ;

            return View(viewModels);
        }

        public IActionResult OIncidents()
        {
            var viewModels = context.Incidents.
                   Include(i => i.Customer).
                   Include(i => i.Product).
                   Include(i => i.Technician).
                   Select(i => new IncidentViewModel
                   {    
                       IncidentId = i.IncidentId,
                       CustomerId = i.CustomerId,
                       Title = i.Title,
                       firstName = i.Customer.FirstName,
                       LastName = i.Customer.LastName,
                       ProductName = i.Product.Name,
                       DateOpened = i.DateOpened,
                       DateClosed = i.DateClosed
                   });

            return View(viewModels);
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            var content = loadContent();
            return View("Edit", content);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var incident = context.Incidents.Find(id);
            var content = loadContent();
            content.IncidentId = incident.IncidentId;
            content.Title = incident.Title;
            content.Description = incident.Description;
            content.DateOpened = incident.DateOpened;
            content.DateClosed = incident.DateClosed;
            content.ProductId = incident.ProductId;
            content.TechnicianId = incident.TechnicianId;
            content.CustomerId = incident.CustomerId;

            return View(content);
        }

        [HttpPost]
        public IActionResult Edit(IncidentViewModel incident)
        {
            Incident model = new()
            {
                IncidentId = incident.IncidentId,
                ProductId = incident.ProductId,
                CustomerId = incident.CustomerId,
                Title = incident.Title,
                DateOpened = incident.DateOpened,
                DateClosed = incident.DateClosed,
                Description = incident.Description,
                TechnicianId = incident.TechnicianId
            };

            if (ModelState.IsValid)
            {
                if (model.IncidentId == 0)
                {
                    context.Incidents.Add(model);
                    TempData["message"] = $"<{model.Title}> Incident was Added!";
                }
                else
                {
                    context.Incidents.Update(model);
                    TempData["message"] = $"<{model.Title}> Incident was Updated!";
                }
                context.SaveChanges();
                return RedirectToAction("Incidents", "Home");
            }
            else
            {
                ViewBag.Action = (model.IncidentId == 0) ? "Add" : "Edit";
                var content = loadContent();
                content.IncidentId = incident.IncidentId;
                content.Title = incident.Title;
                content.Description = incident.Description;
                content.DateOpened = incident.DateOpened;
                content.DateClosed = incident.DateClosed;
                content.ProductId = incident.ProductId;
                content.TechnicianId = incident.TechnicianId;
                return View(content);
            }
            
        }

        [HttpGet]
        public IActionResult Delete(int id, int cid)
        {

            var incident = context.Incidents.Find(id);
            var customer = context.Customers.Find(cid);
            var vm = new IncidentViewModel
            {
                
                Title = incident.Title,
                firstName = customer.FirstName,
                LastName = customer.LastName,
                IncidentId = incident.IncidentId
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Delete(IncidentViewModel incident)
        {

            var model = context.Incidents.Find(incident.IncidentId);


            context.Incidents.Remove(model);
            context.SaveChanges();
            TempData["message"] = $"<{model.Title}> Incident was Deleted!";
            return RedirectToAction("Incidents", "Home");
        }

        public IncidentViewModel loadContent()
        {
            var vm = new IncidentViewModel();
            var customers = context.Customers;
            var products = context.Products;
            var technicians = context.Technicians;

            var customerList = customers.Select(
                c => new SelectListItem
                {
                    Text = c.FirstName + " " + c.LastName,
                    Value = c.CustomerId.ToString(),
                }).ToList();

            var productList = products.Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.ProductId.ToString()
                }).ToList();

            var technicianList = technicians.Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.TechnicianId.ToString()
                }).ToList();

            vm.Customers = customerList;
            vm.Products = productList;
            vm.Technicians = technicianList;
            return vm;
        }
    }
}

Controllers/ProductController.cs
using GBCSporting_X_TEAM.Models;
using Microsoft.AspNetCore.Mvc;

namespace GBCSporting_X_TEAM.Controllers
{
    public class ProductController : Controller
    {
        private GbcSportingContext context { get; set; }

        public ProductController(GbcSportingContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("Edit", new Product());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var product = context.Products.Find(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ProductId == 0)
                {
                    context.Products.Add(product);
                    TempData["message"] = $"{product.Name} was added!";
                }
                else
                {
                    context.Products.Update(product);
                    TempData["message"] = $"{product.Name} was updated!";
                }
                context.SaveChanges();
                return RedirectToAction("Products", "Home");
            }
            else
            {
                ViewBag.Action = (product.ProductId == 0) ? "Add" : "Edit";
                return View(product);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = context.Products.Find(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            context.Products.Remove(product);
            context.SaveChanges();
            TempData["message"] = $"model was deleted!";
            return RedirectToAction("Products", "Home");
        }
    }
}

Controllers/TechnicianController.cs
using GBCSporting_X_TEAM.Models;
using Microsoft.AspNetCore.Mvc;

namespace GBCSporting_X_TEAM.Controllers
{
    public class TechnicianController : Controller
    {
        private GbcSportingContext context { get; set; }

        public TechnicianController(GbcSportingContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("Edit", new Technician());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var technician = context.Technicians.Find(id);
            return View(technician);
        }

        [HttpPost]
        public IActionResult Edit(Technician technician)
        {
            if (ModelState.IsValid)
            {
                if (technician.TechnicianId == 0)
                    context.Technicians.Add(technician);
                else
                    context.Technicians.Update(technician);
                context.SaveChanges();
                return RedirectToAction("Technicians", "Home");
            }
            else
            {
                ViewBag.Action = (technician.TechnicianId == 0) ? "Add" : "Edit";
                return View(technician);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var technician = context.Technicians.Find(id);
            return View(technician);
        }

        [HttpPost]
        public IActionResult Delete(Technician technician)
        {
            context.Technicians.Remove(technician);
            context.SaveChanges();
            return RedirectToAction("Technicians", "Home");
        }


    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Gbc Sport";
}

<div class=" container tb-wrapper w-75">
     <div class="table-title">
            <div class="row">
                <div class="col-sm-6"><h2>@ViewData["Title"]</h2></div>
               
            </div>
    
        </div>
                <h3>Here at GbcSport we believe that great software is only as good as the support its given.</h3>
                <h4>To that end we believe in software support that is</h4>
                <ol>
                    <h4>Timely</h4>
                    <ul>
                        <li>What good is support if takes weeks to solve your issues? Time is money. </li>
                    </ul>
                    
                    <h4>Well documented</h4>
                    <ul>
                        <li>We pride ourselves on creating and providing useful documentation for all the products we support</li>
                    </ul>

                    
                    <h4>Customer centric</h4>
                    <ul>
                        <li> We have a no nonsense policy, if it doesnt help you we dont support it</li>
                         
                    </ul>

                    <h4>Honest</h4>
                    <ul>
                        <li> We will never take advantage of our customers and are upfront up with our costs</li>
                    </ul>

                </ol>
</div>

Views/Home/Customers.cshtml
@model List<Customer>
@{
    ViewData["Title"] = "Customer Manager";
}

<div class=" container tb-wrapper">
     <div class="table-title">
            <div class="row">
                <div class="col-sm-6"><h2>@ViewData["Title"]</h2></div>

            </div>
        </div>
    
    <table class="table table-bordered tbl-hover">
    <thead class="thead">
        <tr><th>Name</th><th>Email</th><th>City</th><th>Action</th></tr>
    </thead>
    <tbody>
        @foreach (var customer in Model) {
            <tr>
                <td>@customer.FirstName @customer.LastName</td>
                <td>@customer.Email</td>
                <td>@customer.City</td>
                <td>
                    <a class=" btn btn-primary btn-sm rounded-2 main-blue " asp-controller="Customer" asp-action="Edit"
                       asp-route-id="@customer.CustomerId"
                       asp-route-slug="@customer.Slug"><img height=25 width=25 src="~/img/pencil.png"></a>
                    <a class=" btn btn-danger btn-sm rounded-2" asp-controller="Customer" asp-action="Delete"
                       asp-route-id="@customer.CustomerId"
                       asp-route-slug="@customer.Slug"><img height=25 width=25 src="~/img/delete.png"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary btn-md main-blue" asp-controller="Customer" asp-action="Add">Add Customer</a>
</div>

Views/Home/Incidents.cshtml
@using GBCSporting_X_TEAM.Models.ViewModels
@model IEnumerable<IncidentViewModel>
@{
    ViewData["Title"] = "Incidents";
}


<a class="btn btn-primary btn-md main-blue" asp-controller="Incident" asp-action="AllIncidents">All Incidents</a>
<a class="btn btn-primary btn-md main-blue" asp-controller="Incident" asp-action="UIncidents">Unassigned Incidents</a>
<a class="btn btn-primary btn-md main-blue" asp-controller="Incident" asp-action="OIncidents">Open Incident</a>

<div class=" container tb-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>

        </div>
    </div>


    <table class="table table-bordered tbl-hover tbl-fn-sm">
        <thead class="thead">
            <tr>
                <th>Title</th>
                <th>Customer</th>
                <th>Product</th>
                <th>Date Opened</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var incident in Model)
            {
                <tr>
                    @if(incident.Title.Length > 60){
                        <td><span class="fn-md">@incident.Title</span></td>
                    }else{
                        <td>@incident.Title</td>
                    }
                    <td>@incident.firstName @incident.LastName</td>
                    <td>@incident.ProductName</td>
                    <td>@incident.DateOpened</td>
                     <td class="btn-table">
                        <a class=" btn btn-primary btn-sm rounded-2 main-blue " asp-controller="Incident" asp-action="Edit" asp-route-id="@incident.IncidentId"><img height=25 width=25 src="~/img/pencil.png"></a>
                        <a  class=" btn btn-danger btn-sm rounded-2" asp-controller="Incident" asp-action="Delete" asp-route-id="@incident.IncidentId"
                        asp-route-cid="@incident.CustomerId"><img height=25 width=25 src="~/img/delete.png"> </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-primary btn-md main-blue" asp-controller="Incident" asp-action="Add">Add Incident</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "GBCsport Technical Support";
}


<div class=" container tb-wrapper w-75">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>

        </div>
    </div>
    <h5>Admin Management:</h5>
    <div class="home-index-menu">
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="Products">
                <img src="~/img/product.svg" />
                Products
            </a>
        </div>
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="Technicians">
                <img src="~/img/technician.svg" />
                Technicians
            </a>
        </div>
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="Customers">
                <img src="~/img/customer.svg" />
                Customers
            </a>
        </div>
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="Incidents">
                <img src="~/img/incident.svg" />
                Incidents
            </a>
        </div>
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="Registrations">
                <img src="~/img/registration.svg" />
                Registrations
            </a>
        </div>


    </div>
         <h5>Technician Management:</h5>
        <div class="index-menu-card">
            <a class="list-group-item" asp-area="" asp-controller="Home" asp-action="UpdateIncident">
                <img src="~/img/update.svg" />
                Update Incidents
            </a>
        </div>
</div>

Views/Home/Products.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Products";
}

<div class=" container tb-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>

        </div>
    </div>

    <table class="table table-bordered tbl-hover">
        <thead class="thead">
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Price</th>
                <th>Release Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@product.Code</td>
                    <td>@product.Name</td>
                    <td>@product.Price</td>
                    <td>@product.ReleaseDate</td>



                    <td class="btn-table">
                        <a class=" btn btn-primary btn-sm rounded-2 main-blue " asp-controller="Product" asp-action="Edit"
                        asp-route-id="@product.ProductId" asp-route-slug="@product.Slug"><img height=25 width=25
                            src="~/img/pencil.png"></a>
                        <a class=" btn btn-danger btn-sm rounded-2" asp-controller="Product" asp-action="Delete"
                        asp-route-id="@product.ProductId" asp-route-slug="@product.Slug"><img height=25 width=25
                            src="~/img/delete.png"></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-primary btn-md main-blue" asp-controller="Product" asp-action="Add">Add Product</a>
</div>

Views/Home/Registrations.cshtml
@model Customer
@{
    ViewData["Title"] = "Select Customer";

}

<div class="frm-wrapper w-75">
        <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>

        </div>
    </div>
    <form asp-action="Index" asp-controller="Registration" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        
        <select class="custom-select" asp-for="FirstName" name="custId" required>
            <option value="">Please select a Customer</option>
            @foreach(var customer in ViewBag.Customer)
            {
                <option value="@customer.CustomerId" >@customer.FirstName @customer.LastName</option>
            }
        </select> 
        
    </div>
    
    <button type="submit" class="btn btn-primary">Select</button>
</form>
</div>

Views/Home/Technicians.cshtml
@model List<Technician>
@{
    ViewData["Title"] = "Technicians";
}

<div class=" container tb-wrapper">
     <div class="table-title">
            <div class="row">
                <div class="col-sm-6"><h2>@ViewData["Title"]</h2></div>

            </div>
        </div>


<table class="table table-bordered tbl-hover">
    <thead class="thead">
        <tr><th>Name</th><th>Email</th><th>Phone</th><th>Action</th></tr>
    </thead>
    <tbody>
        @foreach (var technician in Model) {
            <tr class="btn-table">
                <td>@technician.Name</td>
                <td>@technician.Email</td>
                <td>@technician.Phone</td>
                <td>
                    <a class=" btn btn-primary btn-sm rounded-2 main-blue " asp-controller="Technician" asp-action="Edit"
                       asp-route-id="@technician.TechnicianId"><img height=25 width=25 src="~/img/pencil.png"></a>
                    <a class=" btn btn-danger btn-sm rounded-2" asp-controller="Technician" asp-action="Delete"
                       asp-route-id="@technician.TechnicianId"><img height=25 width=25 src="~/img/delete.png"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary btn-md main-blue" asp-controller="Technician" asp-action="Add">Add Technician</a>
</div>

Views/Home/UpdateIncident.cshtml
@using GBCSporting_X_TEAM.Models.ViewModels
@model IncidentViewModel

@{
    ViewData["Title"] = "Update Incident";
    //NameValueCollection nvc = Request.Form;

}

<div class="frm-wrapper w-75">
   <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>@ViewData["Title"]</h2>
            </div>
                  </div>
    </div>
<form asp-action="Index" asp-controller="UpdateIncident" method="Post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        
        <label>Technician:</label>
        <select asp-for="TechnicianId" name="techId" class="form-control">
            <option value="">Select a technician</option>
            @foreach(SelectListItem c in Model.Technicians)
            {
                <option value="@c.Value">@c.Text</option>
            }
        </select>
        
        
    </div>
   
    <button type="submit" class="btn btn-primary">Select</button>
</form>
</div>